name: Solar System Unit Test

on:
  # workflow_dispatch:
  push:
    # branches:
    #   - main
    #   - "feature/*"

env:
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  MONGO_URI: ${{ secrets.MONGO_URI }}
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    name: Unit Testing
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup NodeJS Version
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Node Dependencies
        run: npm install
      # - name: Run Tests
      #   run: npm test
      - name: Generate file
        run: ls  /etc >  test-results.md
      - name: Print file contents
        run: cat test-results.md
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results.md
          path: test-results.md
